[package]
name = "fluxy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
log = { version = "0.4.22", optional = true }
stderrlog = { version = "0.6.0", optional = true }
fake = "3.0.1"
reqwest = "0.12.9"
tokio-task-pool = "0.1.5"
async-trait = "0.1.83"
scraper = { version = "0.21.0", default-features = false, features = ["atomic"] }

[lib]
path = "src/lib.rs"

[[bin]]
name = "fluxy"

[features]
default = ["log"]
log = ["stderrlog", "dep:log"]
